server:
  port: 8080
spring:
  application:
    name: test_task
  datasource:
    url: jdbc:postgresql://localhost:5432/test_task
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue: invoice.send.queue
  data:
    redis:
      host: localhost
      port: 6379
retryable-task:
  limit: 20
  timeout-in-seconds: 30
  scheduler:
    rate: 10000
